
export enum JobStatus {
  OPEN = 'Open',
  CLOSED = 'Closed',
  DRAFT = 'Draft',
}

export enum CandidateStatus {
  APPLIED = 'Applied',
  SCREENING = 'Screening',
  INTERVIEW = 'Interview',
  OFFER = 'Offer',
  HIRED = 'Hired',
  REJECTED = 'Rejected',
}

export interface JobViewer {
  name: string;
  location: string;
  viewedAt: string;
}

export interface Job {
  id: string;
  title: string;
  department: string;
  location: string;
  type: string;
  status: JobStatus;
  description: string;
  requirements: string;
  postedDate: string;
  salaryRange?: string;
  interviewProcess?: string[]; // Generated by AI
  viewers?: JobViewer[];
}

export interface Candidate {
  id: string;
  jobId: string;
  name: string;
  email: string;
  phone: string;
  status: CandidateStatus;
  resumeText: string; // Simplified for demo purposes (instead of PDF parsing)
  appliedDate: string;
  onboardingPlan?: string; // Generated by AI
  aiReview?: {
    score: number;
    summary: string;
    pros: string[];
    cons: string[];
    matchAnalysis: string;
  };
}

export interface DashboardStats {
  totalJobs: number;
  totalCandidates: number;
  activeProcesses: number;
  placementsThisMonth: number;
}

export interface BlogPost {
  id: string;
  title: string;
  excerpt: string;
  content: string;
  author: string;
  date: string;
  imageUrl: string;
  category: string;
}
